version: '3.9'

services:

  selfdev-avatar:
    # hostname: selfdev-avatar.${DOMAIN}
    image: selfdev-avatar:v0.0.1
    build:
      context: ./
    restart: unless-stopped
    shm_size: '2gb'
    ports:
      - 8533:8533
    volumes:
      - ./src:/opt/app/src
    #   - ./data:/opt/app/data
    #   - avatar-volume:/opt/app/data

# volumes:
  # avatar-volume:
