version: '3.9'

services:

  selfdev-avatar:
    # hostname: selfdev-avatar.${DOMAIN}
    image: selfdev-avatar:v0.0.1
    build:
      context: ./
    command: nodemon --exec python src/avatar.py
    # command: /bin/bash -c "sleep 3000"
    restart: unless-stopped
    ports:
      - 8533:8533
    # volumes:
    #   - avatar-volume:/opt/app/data

# volumes:
  # avatar-volume:
