version: '3.9'
services:

  standalone:
    platform: ${PLATFORM}
    image: ${REGISTRY}h9y:${VERSION}
    build:
      context: ./
      args:
        - COMPOSE_PROFILES=standalone
    ports:
      - 3990:3990    # app
      - 6369:6369    # api
      - 6370:6370    # bridge
      - 5281:5281    # prosody wss, https
    volumes:
      - h9y-api-volume:/opt/data/
      - h9y-mongo-volume:/data/db
      - h9y-prosody-volume:/var/lib/prosody/
      - ./selfdev-api/src:/opt/api/src
      - ./selfdev-app/src:/opt/app/src
      - ./selfdev-agency/src:/opt/agency/src

volumes:
  h9y-api-volume:
  h9y-mongo-volume:
  h9y-prosody-volume:

