version: '3.9'
services:

  standalone:
    platform: ${PLATFORM}
    image: ${REGISTRY}h9y-standalone:${VERSION}
    build:
      context: ./
    ports:
      - 3990:3990    # app
      - 6369:6369    # api
      - 6370:6370    # bridge
      - 5280:5280    # prosody http/ws
    volumes:
      - h9y-standalone-volume:/var/lib/
      - ./selfdev-api/src:/opt/api/src
      - ./selfdev-app/src:/opt/app/src
      - ./selfdev-agency/src:/opt/agency/src
      - ./selfdev-prosody/prosody.cfg.lua:/etc/prosody/prosody.cfg.lua

volumes:
  h9y-standalone-volume:

