// GENERATED FILE — do not edit by hand.
//
// Regenerate from the procurement service:
//   docker compose exec h9y-procurement \
//     python -m tools.generate_bff_allowlist \
//     --out /path/to/selfdev-api/src/routes/procurementEndpoints.js
//
// Paths are OpenAPI templates. `procurement.js` compiles each `{param}` to a
// single non-slash segment, so a parameter can never absorb extra path
// segments and reach an endpoint that is not listed here.

export const PROCUREMENT_ENDPOINTS = [
  { method: 'GET', path: '/activity' },
  { method: 'GET', path: '/analytics/benchmark' },
  { method: 'PUT', path: '/analytics/benchmark/baseline' },
  { method: 'GET', path: '/analytics/bottlenecks' },
  { method: 'GET', path: '/analytics/channel-health' },
  { method: 'GET', path: '/analytics/cycle-time' },
  { method: 'GET', path: '/analytics/funnel' },
  { method: 'GET', path: '/analytics/offer-quality' },
  { method: 'GET', path: '/analytics/supply-base' },
  { method: 'GET', path: '/analytics/trends' },
  { method: 'GET', path: '/capabilities' },
  { method: 'GET', path: '/card-imports' },
  { method: 'POST', path: '/card-imports' },
  { method: 'GET', path: '/card-imports/{import_id}' },
  { method: 'POST', path: '/card-imports/{import_id}/cancel' },
  { method: 'POST', path: '/card-imports/{import_id}/confirm' },
  { method: 'PATCH', path: '/card-imports/{import_id}/mapping' },
  { method: 'POST', path: '/card-imports/{import_id}/normalize' },
  { method: 'GET', path: '/cards' },
  { method: 'POST', path: '/cards' },
  { method: 'GET', path: '/cards/{card_id}' },
  { method: 'PATCH', path: '/cards/{card_id}' },
  { method: 'GET', path: '/cards/{card_id}/echemi' },
  { method: 'GET', path: '/cards/{card_id}/echemi/browser-access' },
  { method: 'POST', path: '/cards/{card_id}/echemi/inquiries' },
  { method: 'POST', path: '/cards/{card_id}/echemi/inquiries/{inquiry_id}/approve' },
  { method: 'POST', path: '/cards/{card_id}/echemi/inquiries/{inquiry_id}/preview' },
  { method: 'POST', path: '/cards/{card_id}/echemi/inquiries/{inquiry_id}/submit' },
  { method: 'POST', path: '/cards/{card_id}/echemi/listings/{product_id}/supplier' },
  { method: 'POST', path: '/cards/{card_id}/echemi/search' },
  { method: 'POST', path: '/cards/{card_id}/normalize' },
  { method: 'GET', path: '/cards/{card_id}/rfq' },
  { method: 'PATCH', path: '/cards/{card_id}/rfq' },
  { method: 'POST', path: '/cards/{card_id}/rfq/approve' },
  { method: 'POST', path: '/cards/{card_id}/rfq/prepare' },
  { method: 'GET', path: '/cards/{card_id}/sourcing' },
  { method: 'POST', path: '/cards/{card_id}/sourcing/runs' },
  { method: 'GET', path: '/communication/compositions' },
  { method: 'GET', path: '/communication/compositions/{composition_id}' },
  { method: 'POST', path: '/communication/compositions/{composition_id}/approve' },
  { method: 'POST', path: '/communication/compositions/{composition_id}/reject' },
  { method: 'GET', path: '/communication/imports' },
  { method: 'POST', path: '/communication/imports' },
  { method: 'GET', path: '/communication/imports/{import_id}' },
  { method: 'POST', path: '/communication/imports/{import_id}/cancel' },
  { method: 'POST', path: '/communication/imports/{import_id}/confirm' },
  { method: 'GET', path: '/communication/performance' },
  { method: 'GET', path: '/communication/playbook' },
  { method: 'POST', path: '/communication/playbook' },
  { method: 'POST', path: '/communication/playbook/preview' },
  { method: 'GET', path: '/communication/playbook/{item_id}' },
  { method: 'PATCH', path: '/communication/playbook/{item_id}' },
  { method: 'GET', path: '/communication/playbook/{item_id}/usage' },
  { method: 'GET', path: '/communication/policy' },
  { method: 'PUT', path: '/communication/policy' },
  { method: 'POST', path: '/communication/simulate' },
  { method: 'GET', path: '/communication/vocabulary' },
  { method: 'GET', path: '/escalations' },
  { method: 'GET', path: '/escalations/{escalation_id}' },
  { method: 'POST', path: '/escalations/{escalation_id}/claim' },
  { method: 'POST', path: '/escalations/{escalation_id}/recommendations' },
  { method: 'POST', path: '/escalations/{escalation_id}/resolution' },
  { method: 'GET', path: '/negotiations' },
  { method: 'POST', path: '/negotiations' },
  { method: 'GET', path: '/negotiations/activity' },
  { method: 'GET', path: '/negotiations/quarantine' },
  { method: 'POST', path: '/negotiations/quarantine/{message_id}/assign' },
  { method: 'POST', path: '/negotiations/quarantine/{message_id}/dismiss' },
  { method: 'GET', path: '/negotiations/{negotiation_id}' },
  { method: 'POST', path: '/negotiations/{negotiation_id}/follow-up' },
  { method: 'POST', path: '/negotiations/{negotiation_id}/queue' },
  { method: 'POST', path: '/negotiations/{negotiation_id}/responses' },
  { method: 'GET', path: '/negotiations/{negotiation_id}/web-form' },
  { method: 'POST', path: '/negotiations/{negotiation_id}/web-form/approve' },
  { method: 'POST', path: '/negotiations/{negotiation_id}/web-form/prepare' },
  { method: 'POST', path: '/negotiations/{negotiation_id}/web-form/preview' },
  { method: 'POST', path: '/negotiations/{negotiation_id}/web-form/submit' },
  { method: 'GET', path: '/overview' },
  { method: 'GET', path: '/overview/board' },
  { method: 'GET', path: '/proposals' },
  { method: 'GET', path: '/proposals/compare' },
  { method: 'GET', path: '/proposals/export' },
  { method: 'GET', path: '/proposals/{response_id}' },
  { method: 'POST', path: '/proposals/{response_id}/clarification' },
  { method: 'GET', path: '/settings/buyer' },
  { method: 'PUT', path: '/settings/buyer' },
  { method: 'GET', path: '/sourcing/engines' },
  { method: 'GET', path: '/sourcing/query-templates' },
  { method: 'PUT', path: '/sourcing/query-templates' },
  { method: 'GET', path: '/sourcing/{run_id}' },
  { method: 'POST', path: '/sourcing/{run_id}/cancel' },
  { method: 'POST', path: '/sourcing/{run_id}/candidates/{candidate_id}/promote' },
  { method: 'POST', path: '/sourcing/{run_id}/candidates/{candidate_id}/review' },
  { method: 'POST', path: '/sourcing/{run_id}/sources' },
  { method: 'POST', path: '/sourcing/{run_id}/sources/{source_id}/retry' },
  { method: 'GET', path: '/supplier-response-attachments/{attachment_id}' },
  { method: 'GET', path: '/suppliers' },
  { method: 'POST', path: '/suppliers' },
  { method: 'GET', path: '/suppliers/{supplier_id}' },
  { method: 'PATCH', path: '/suppliers/{supplier_id}' },
  { method: 'POST', path: '/suppliers/{supplier_id}/capabilities' },
  { method: 'POST', path: '/suppliers/{supplier_id}/contacts' },
  { method: 'PATCH', path: '/suppliers/{supplier_id}/contacts/{contact_id}' },
  { method: 'PATCH', path: '/suppliers/{supplier_id}/qualification' },
  { method: 'GET', path: '/web-form/adapters' },
]
