export const procurementKeys = {
  all: ['procurement'],
  overview: () => [...procurementKeys.all, 'overview'],
  cards: filters => [...procurementKeys.all, 'cards', filters],
  card: id => [...procurementKeys.all, 'card', String(id)],
  rfq: id => [...procurementKeys.all, 'rfq', String(id)],
  echemi: id => [...procurementKeys.all, 'echemi', String(id)],
  echemiBrowserAccess: id => [...procurementKeys.all, 'echemi-browser-access', String(id)],
  sourcing: id => [...procurementKeys.all, 'sourcing', String(id)],
  sourcingRun: runId => [...procurementKeys.all, 'sourcing-run', String(runId)],
  suppliers: filters => [...procurementKeys.all, 'suppliers', filters],
  supplier: id => [...procurementKeys.all, 'supplier', id],
  negotiations: filters => [...procurementKeys.all, 'negotiations', filters],
  negotiation: id => [...procurementKeys.all, 'negotiation', id],
  proposals: filters => [...procurementKeys.all, 'proposals', filters],
  proposal: id => [...procurementKeys.all, 'proposal', id],
  comparison: cardId => [...procurementKeys.all, 'comparison', String(cardId)],
  escalations: filters => [...procurementKeys.all, 'escalations', filters],
  escalation: id => [...procurementKeys.all, 'escalation', id],
  activity: filters => [...procurementKeys.all, 'activity', filters],
}
