FROM 42wim/matterbridge:1.26 AS matterbridge
FROM node:22-alpine

COPY --from=matterbridge /bin/matterbridge /bin/matterbridge

RUN apk add --no-cache bash curl wget git make gcc g++ python3 expect openssl

# Install and enable Corepack
RUN npm install -g corepack@latest && corepack enable
RUN corepack prepare pnpm@10.34.4 --activate
# 👇 Define PNPM_HOME and update PATH so global packages work
ENV PNPM_HOME="/usr/local/share/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN mkdir -p $PNPM_HOME && chmod -R 755 $PNPM_HOME
# RUN pnpm add -g @lowdefy/cli@4.5.2
RUN pnpm add -g lowdefy@4.5.2


WORKDIR /opt/app/
COPY package*.json ./
RUN npm install
COPY . .

ENTRYPOINT ["npm"]
CMD ["run", "bridge"]
